version: "3.8"
services:
  # PHP service
  user:
    build: ./Autobahn-User
    container_name: service-user
    working_dir: /var/www/
    volumes:
      - ./Autobahn-User:/var/www
      - ./Autobahn-User/vendor:/var/www/vendor
    networks:
      - app-network

  car:
    build: ./Autobahn-Car
    container_name: service-car
    working_dir: /var/www
    volumes:
      - ./Autobahn-Car:/var/www
    environment:
      FLASK_ENV: development
    networks:
      - app-network

  proxy:
    build:
      context: ./Autobahn-Proxy
    container_name: service-proxy
    working_dir: /var/www/
    volumes:
      - ./Autobahn-Proxy:/var/www
    networks:
      - app-network
    ports:
      - 8000:8000

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autobahn_user
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: php-nginx
    volumes:
      - ./Autobahn-User:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge