version: "3.8"
services:
  # MySQL database service
  db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autobahn_user
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    networks:
      - app-network

  app:
    build: ./Autobahn-User
    container_name: php-app
    working_dir: /var/www/
    volumes:
      - ./Autobahn-User:/var/www
      - ./Autobahn-User/vendor:/var/www/vendor
    networks:
      - app-network
    ports:
      - 9000:9000

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: php-nginx
    ports:
      - 8000:80
    volumes:
      - ./Autobahn-User:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
